In [9]:
import pandas as pd
import warnings

# Suppress warnings:
warnings.filterwarnings("ignore")

# Importing functions for exploration and cleaning:
import initial_exploration as explo
import data_cleaning as cl

# Autoreload to automatically update modules:
%load_ext autoreload
%autoreload 2

# Display all columns:
pd.set_option('display.max_columns', None)

# Load datasets:
cash_requests = pd.read_csv('project_dataset/extract - cash request - data analyst.csv')
fees = pd.read_csv('project_dataset/extract - fees - data analyst - .csv')

# Initial exploration on cash_requests:
explo.check(cash_requests)

# Ensure correct data types for cash_requests:
cl.ensure_correct_data_types(cash_requests, cl.cash_request_date_columns)

# Print data types and inspect first few rows:
print(cash_requests.dtypes)
cash_requests.head()

# Initial exploration on fees:
explo.check(fees)

# Ensure correct data types for fees:
cl.ensure_correct_data_types(fees, cl.fees_data_date_columns)

# Print data types and inspect first few rows of fees:
print(fees.dtypes)
fees.head()

# Merging datasets:
data_df = cl.merge_df(cash_requests, fees, 'outer', 'id', 'cash_request_id')

# Inspect the merged data
print(data_df.head())
print(data_df.dtypes)

# Remove NaN values from "id_x":
data_df = cl.remove_nan(data_df, "id_x")

# Check for missing values:
explo.check_null(data_df)

# Selecting data types:
frames = cl.selecting_data_types(data_df)
num, cat = frames[1], frames[0]

# Inspect first few rows of numerical and categorical columns:
print(num.head())  # Numerical columns
print(cat.head())  # Categorical columns

# Re-check and ensure correct data types in cash_requests:
cl.ensure_correct_data_types(cash_requests, cl.cash_request_date_columns)

# Verify specific date columns' data types in cash_requests:
print("\nCheck data types of date columns:")
print(cash_requests[['created_at', 'updated_at', 'reimbursement_date', 
                     'cash_request_received_date', 'money_back_date']].dtypes)

# Check for any NaT in date columns:
print("\nCheck NaT (missing values) in date columns:")
print(cash_requests[['created_at', 'updated_at', 'reimbursement_date', 
                     'cash_request_received_date', 'money_back_date']].isna().sum())

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Number of columns: 16 amd rows: 23970

Data types:
id                              int64
amount                        float64
status                         object
created_at                     object
updated_at                     object
user_id                       float64
moderated_at                   object
deleted_account_id            float64
reimbursement_date             object
cash_request_received_date     object
money_back_date                object
transfer_type                  object
send_at                        object
recovery_status                object
reco_creation                  object
reco_last_update               object
dtype: object

Unique values count:
id                            23970
amount                           41
status                            7
created_at                    23970
updated_at                    23970
user_id                       10798
moderated_at                  16035
deleted_account_id             1141
reimbursement_date             4089
cash_request_received_date      312
money_back_date               12221
transfer_type                     2
send_at                       16641
recovery_status                   4
reco_creation                  3330
reco_last_update               3330
dtype: int64

This columns apear to be categroical:
 Index(['status', 'transfer_type', 'recovery_status'], dtype='object')

Unique value count for categorical columns:
status
money_back               16397
rejected                  6568
direct_debit_rejected      831
active                      59
transaction_declined        48
direct_debit_sent           34
canceled                    33
Name: count, dtype: int64

transfer_type
instant    13882
regular    10088
Name: count, dtype: int64

recovery_status
completed               2468
pending                  845
pending_direct_debit      16
cancelled                  1
Name: count, dtype: int64

Count of null values:
id                                0
amount                            0
status                            0
created_at                        0
updated_at                        0
user_id                        2103
moderated_at                   7935
deleted_account_id            21866
reimbursement_date                0
cash_request_received_date     7681
money_back_date                7427
transfer_type                     0
send_at                        7329
recovery_status               20640
reco_creation                 20640
reco_last_update              20640
dtype: int64

Count of duplicated values:
0
id                                     int64
amount                               float64
status                              category
created_at                    datetime64[ns]
updated_at                    datetime64[ns]
user_id                              float64
moderated_at                  datetime64[ns]
deleted_account_id                   float64
reimbursement_date            datetime64[ns]
cash_request_received_date    datetime64[ns]
money_back_date               datetime64[ns]
transfer_type                       category
send_at                       datetime64[ns]
recovery_status                     category
reco_creation                 datetime64[ns]
reco_last_update              datetime64[ns]
dtype: object
Number of columns: 13 amd rows: 21061

Data types:
id                   int64
cash_request_id    float64
type                object
status              object
category            object
total_amount       float64
reason              object
created_at          object
updated_at          object
paid_at             object
from_date           object
to_date             object
charge_moment       object
dtype: object

Unique values count:
id                 21061
cash_request_id    12933
type                   3
status                 4
category               2
total_amount           2
reason             15149
created_at         21026
updated_at         21061
paid_at            15529
from_date           1084
to_date             1560
charge_moment          2
dtype: int64

This columns apear to be categroical:
 Index(['type', 'status', 'category', 'total_amount', 'charge_moment'], dtype='object')

Unique value count for categorical columns:
type
instant_payment    11099
postpone            7766
incident            2196
Name: count, dtype: int64

status
accepted     14841
cancelled     4938
rejected      1194
confirmed       88
Name: count, dtype: int64

category
rejected_direct_debit     1599
month_delay_on_payment     597
Name: count, dtype: int64

total_amount
5.0     21060
10.0        1
Name: count, dtype: int64

charge_moment
after     16724
before     4337
Name: count, dtype: int64

Count of null values:
id                     0
cash_request_id        4
type                   0
status                 0
category           18865
total_amount           0
reason                 0
created_at             0
updated_at             0
paid_at             5530
from_date          13295
to_date            13295
charge_moment          0
dtype: int64

Count of duplicated values:
0
id                          int64
cash_request_id           float64
type                     category
status                   category
category                 category
total_amount              float64
reason                   category
created_at         datetime64[ns]
updated_at         datetime64[ns]
paid_at            datetime64[ns]
from_date          datetime64[ns]
to_date            datetime64[ns]
charge_moment      datetime64[ns]
dtype: object
     id_x  amount  status_x created_at_x updated_at_x  user_id moderated_at  \
0     5.0   100.0  rejected          NaT          NaT    804.0          NaT
1    70.0   100.0  rejected          NaT          NaT    231.0          NaT
2     7.0   100.0  rejected          NaT          NaT    191.0          NaT
3    10.0    99.0  rejected          NaT          NaT    761.0          NaT
4  1594.0   100.0  rejected          NaT          NaT   7686.0          NaT

   deleted_account_id reimbursement_date cash_request_received_date  \
0                 NaN                NaT                        NaT
1                 NaN                NaT                        NaT
2                 NaN                NaT                        NaT
3                 NaN                NaT                        NaT
4                 NaN                NaT                        NaT

  money_back_date transfer_type send_at recovery_status reco_creation  \
0             NaT       regular     NaT             NaN           NaT
1             NaT       regular     NaT             NaN           NaT
2             NaT       regular     NaT             NaN           NaT
3             NaT       regular     NaT             NaN           NaT
4             NaT       regular     NaT             NaN           NaT

  reco_last_update  id_y  cash_request_id type status_y category  \
0              NaT   NaN              NaN  NaN      NaN      NaN
1              NaT   NaN              NaN  NaN      NaN      NaN
2              NaT   NaN              NaN  NaN      NaN      NaN
3              NaT   NaN              NaN  NaN      NaN      NaN
4              NaT   NaN              NaN  NaN      NaN      NaN

   total_amount reason created_at_y updated_at_y paid_at from_date to_date  \
0           NaN    NaN          NaT          NaT     NaT       NaT     NaT
1           NaN    NaN          NaT          NaT     NaT       NaT     NaT
2           NaN    NaN          NaT          NaT     NaT       NaT     NaT
3           NaN    NaN          NaT          NaT     NaT       NaT     NaT
4           NaN    NaN          NaT          NaT     NaT       NaT     NaT

  charge_moment
0           NaT
1           NaT
2           NaT
3           NaT
4           NaT
id_x                                 float64
amount                               float64
status_x                            category
created_at_x                  datetime64[ns]
updated_at_x                  datetime64[ns]
user_id                              float64
moderated_at                  datetime64[ns]
deleted_account_id                   float64
reimbursement_date            datetime64[ns]
cash_request_received_date    datetime64[ns]
money_back_date               datetime64[ns]
transfer_type                       category
send_at                       datetime64[ns]
recovery_status                     category
reco_creation                 datetime64[ns]
reco_last_update              datetime64[ns]
id_y                                 float64
cash_request_id                      float64
type                                category
status_y                            category
category                            category
total_amount                         float64
reason                              category
created_at_y                  datetime64[ns]
updated_at_y                  datetime64[ns]
paid_at                       datetime64[ns]
from_date                     datetime64[ns]
to_date                       datetime64[ns]
charge_moment                 datetime64[ns]
dtype: object
4 rows were removed

Count of null values:
id_x                              0
amount                            0
status_x                          0
created_at_x                  32094
updated_at_x                  32094
user_id                        2572
moderated_at                  32094
deleted_account_id            29521
reimbursement_date            32094
cash_request_received_date    32094
money_back_date               32094
transfer_type                     0
send_at                       32094
recovery_status               24894
reco_creation                 32094
reco_last_update              32094
id_y                          11037
cash_request_id               11037
type                          11037
status_y                      11037
category                      29898
total_amount                  11037
reason                        11037
created_at_y                  32094
updated_at_y                  32094
paid_at                       32094
from_date                     32094
to_date                       32094
charge_moment                 32094
dtype: int64
     id_x  amount  user_id  deleted_account_id  id_y  cash_request_id
0     5.0   100.0    804.0                 NaN   NaN              NaN
1    70.0   100.0    231.0                 NaN   NaN              NaN
2     7.0   100.0    191.0                 NaN   NaN              NaN
3    10.0    99.0    761.0                 NaN   NaN              NaN
4  1594.0   100.0   7686.0                 NaN   NaN              NaN
   status_x created_at_x updated_at_x moderated_at reimbursement_date  \
0  rejected          NaT          NaT          NaT                NaT
1  rejected          NaT          NaT          NaT                NaT
2  rejected          NaT          NaT          NaT                NaT
3  rejected          NaT          NaT          NaT                NaT
4  rejected          NaT          NaT          NaT                NaT

  cash_request_received_date money_back_date transfer_type send_at  \
0                        NaT             NaT       regular     NaT
1                        NaT             NaT       regular     NaT
2                        NaT             NaT       regular     NaT
3                        NaT             NaT       regular     NaT
4                        NaT             NaT       regular     NaT

  recovery_status reco_creation reco_last_update type status_y category  \
0             NaN           NaT              NaT  NaN      NaN      NaN
1             NaN           NaT              NaT  NaN      NaN      NaN
2             NaN           NaT              NaT  NaN      NaN      NaN
3             NaN           NaT              NaT  NaN      NaN      NaN
4             NaN           NaT              NaT  NaN      NaN      NaN

  reason created_at_y updated_at_y paid_at from_date to_date charge_moment  \
0    NaN          NaT          NaT     NaT       NaT     NaT           NaT
1    NaN          NaT          NaT     NaT       NaT     NaT           NaT
2    NaN          NaT          NaT     NaT       NaT     NaT           NaT
3    NaN          NaT          NaT     NaT       NaT     NaT           NaT
4    NaN          NaT          NaT     NaT       NaT     NaT           NaT

   total_amount
0           NaN
1           NaN
2           NaN
3           NaN
4           NaN

Check data types of date columns:
created_at                    datetime64[ns]
updated_at                    datetime64[ns]
reimbursement_date            datetime64[ns]
cash_request_received_date    datetime64[ns]
money_back_date               datetime64[ns]
dtype: object

Check NaT (missing values) in date columns:
created_at                    23970
updated_at                    23970
reimbursement_date            23970
cash_request_received_date    23970
money_back_date               23970
dtype: int64